spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookobook
    username: postgres
    password: "112358"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: ged
      password: 112358